version: "3"
services:
  web:
    image: nginx
    ports:
    - ${EXPOSE_PORT:-8080}:80
    volumes:
    - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
  aliasmanager-client:
    image: dploeger/aliasmanager-client:latest
  aliasmanager:
    image: dploeger/aliasmanager
    env_file:
      - ".env"
